# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.contrib.gis.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxaProdes',
            fields=[
                ('ano_prodes', models.CharField(serialize=False, primary_key=True, blank=True, max_length=9)),
                ('ac', models.DecimalField(decimal_places=2, blank=True, max_digits=7)),
                ('am', models.DecimalField(decimal_places=2, blank=True, max_digits=7)),
                ('ap', models.DecimalField(decimal_places=2, blank=True, max_digits=7)),
                ('ma', models.DecimalField(decimal_places=2, blank=True, max_digits=7)),
                ('mt', models.DecimalField(decimal_places=2, blank=True, max_digits=7)),
                ('pa', models.DecimalField(decimal_places=2, blank=True, max_digits=7)),
                ('ro', models.DecimalField(decimal_places=2, blank=True, max_digits=7)),
                ('rr', models.DecimalField(decimal_places=2, blank=True, max_digits=7)),
                ('to', models.DecimalField(decimal_places=2, blank=True, max_digits=7)),
            ],
            options={
                'managed': False,
                'db_table': 'taxa_prodes',
            },
        ),
        migrations.CreateModel(
            name='DailyAlertaAwifs',
            fields=[
                ('objectid', models.AutoField(serialize=False, primary_key=True)),
                ('mes', models.CharField(null=True, blank=True, max_length=10)),
                ('ano', models.SmallIntegerField(null=True, blank=True)),
                ('area_km2', models.DecimalField(decimal_places=2, null=True, blank=True, max_digits=38)),
                ('dominio', models.CharField(null=True, blank=True, max_length=200)),
                ('tipo', models.CharField(null=True, blank=True, max_length=15)),
                ('uf', models.SmallIntegerField(null=True, blank=True)),
                ('estado', models.CharField(null=True, blank=True, max_length=2)),
                ('data_imagem', models.DateTimeField(null=True, blank=True)),
                ('shape', django.contrib.gis.db.models.fields.GeometryField(srid=4326, null=True, blank=True)),
                ('centroide', django.contrib.gis.db.models.fields.GeometryField(srid=4326, null=True, blank=True)),
                ('mesid', models.TextField(null=True, blank=True)),
                ('estagio', models.CharField(null=True, blank=True, max_length=50)),
                ('periodo_prodes', models.CharField(null=True, blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DailyAlertaDeter',
            fields=[
                ('objectid', models.AutoField(serialize=False, primary_key=True)),
                ('mes', models.CharField(null=True, blank=True, max_length=10)),
                ('ano', models.SmallIntegerField(null=True, blank=True)),
                ('area_km2', models.DecimalField(decimal_places=2, null=True, blank=True, max_digits=38)),
                ('dominio', models.CharField(null=True, blank=True, max_length=200)),
                ('tipo', models.CharField(null=True, blank=True, max_length=15)),
                ('uf', models.SmallIntegerField(null=True, blank=True)),
                ('estado', models.CharField(null=True, blank=True, max_length=2)),
                ('data_imagem', models.DateTimeField(null=True, blank=True)),
                ('shape', django.contrib.gis.db.models.fields.GeometryField(srid=4326, null=True, blank=True)),
                ('centroide', django.contrib.gis.db.models.fields.GeometryField(srid=4326, null=True, blank=True)),
                ('mesid', models.TextField(null=True, blank=True)),
                ('estagio', models.CharField(null=True, blank=True, max_length=50)),
                ('periodo_prodes', models.CharField(null=True, blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DailyAlertaDeterQualif',
            fields=[
                ('objectid', models.AutoField(serialize=False, primary_key=True)),
                ('periodo_prodes', models.CharField(null=True, blank=True, max_length=10)),
                ('mes', models.CharField(null=True, blank=True, max_length=10)),
                ('ano', models.SmallIntegerField(null=True, blank=True)),
                ('mes_ano', models.CharField(null=True, blank=True, max_length=6)),
                ('cicatriz_fogo', models.DecimalField(decimal_places=2, null=True, blank=True, max_digits=6)),
                ('corte_raso_deter', models.DecimalField(decimal_places=2, null=True, blank=True, max_digits=6)),
                ('degradacao_deter', models.DecimalField(decimal_places=2, null=True, blank=True, max_digits=6)),
                ('alta', models.DecimalField(decimal_places=2, null=True, blank=True, max_digits=6)),
                ('leve', models.DecimalField(decimal_places=2, null=True, blank=True, max_digits=6)),
                ('moderada', models.DecimalField(decimal_places=2, null=True, blank=True, max_digits=6)),
                ('falso_positivo', models.DecimalField(decimal_places=2, null=True, blank=True, max_digits=6)),
                ('nao_avaliado', models.DecimalField(decimal_places=2, null=True, blank=True, max_digits=6)),
                ('deter_total', models.DecimalField(decimal_places=2, null=True, blank=True, max_digits=6)),
                ('total_avaliado', models.DecimalField(decimal_places=2, null=True, blank=True, max_digits=6)),
                ('porc_area_avaliada', models.SmallIntegerField(null=True, blank=True)),
                ('mesid', models.TextField(null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyAlertaLandsat',
            fields=[
                ('objectid', models.AutoField(serialize=False, primary_key=True)),
                ('mes', models.CharField(null=True, blank=True, max_length=10)),
                ('ano', models.SmallIntegerField(null=True, blank=True)),
                ('area_km2', models.DecimalField(decimal_places=2, null=True, blank=True, max_digits=38)),
                ('dominio', models.CharField(null=True, blank=True, max_length=200)),
                ('tipo', models.CharField(null=True, blank=True, max_length=15)),
                ('uf', models.SmallIntegerField(null=True, blank=True)),
                ('estado', models.CharField(null=True, blank=True, max_length=2)),
                ('data_imagem', models.DateTimeField(null=True, blank=True)),
                ('shape', django.contrib.gis.db.models.fields.GeometryField(srid=4326, null=True, blank=True)),
                ('centroide', django.contrib.gis.db.models.fields.GeometryField(srid=4326, null=True, blank=True)),
                ('mesid', models.TextField(null=True, blank=True)),
                ('estagio', models.CharField(null=True, blank=True, max_length=50)),
                ('periodo_prodes', models.CharField(null=True, blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PublicAlertaDeter',
            fields=[
                ('objectid', models.AutoField(serialize=False, primary_key=True)),
                ('mes', models.CharField(null=True, blank=True, max_length=10)),
                ('ano', models.SmallIntegerField(null=True, blank=True)),
                ('area_km2', models.DecimalField(decimal_places=8, null=True, blank=True, max_digits=38)),
                ('area_ha', models.DecimalField(decimal_places=8, null=True, blank=True, max_digits=38)),
                ('municipio', models.CharField(null=True, blank=True, max_length=200)),
                ('dominio', models.CharField(null=True, blank=True, max_length=200)),
                ('tipo', models.CharField(null=True, blank=True, max_length=15)),
                ('quinzena', models.CharField(null=True, blank=True, max_length=5)),
                ('id_des', models.CharField(unique=True, null=True, blank=True, max_length=16)),
                ('ai', models.IntegerField(null=True, blank=True)),
                ('tei', models.IntegerField(null=True, blank=True)),
                ('processo', models.CharField(null=True, blank=True, max_length=20)),
                ('url', models.CharField(null=True, blank=True, max_length=200)),
                ('vistoria', models.CharField(null=True, blank=True, max_length=100)),
                ('resp_vistoria', models.CharField(null=True, blank=True, max_length=150)),
                ('longitude', models.CharField(null=True, blank=True, max_length=17)),
                ('latitude', models.CharField(null=True, blank=True, max_length=17)),
                ('uf', models.SmallIntegerField(null=True, blank=True)),
                ('estado', models.CharField(null=True, blank=True, max_length=2)),
                ('obs', models.CharField(null=True, blank=True, max_length=250)),
                ('id_tablet', models.CharField(null=True, blank=True, max_length=10)),
                ('data_vist', models.CharField(null=True, blank=True, max_length=50)),
                ('globalid', models.CharField(null=True, blank=True, max_length=50)),
                ('dado_final', models.CharField(null=True, blank=True, max_length=1)),
                ('estagio', models.CharField(null=True, blank=True, max_length=50)),
                ('data_imagem', models.DateTimeField(null=True, blank=True)),
                ('shape', django.contrib.gis.db.models.fields.GeometryField(srid=4326, null=True, blank=True)),
                ('veg_sec', models.CharField(null=True, blank=True, max_length=100)),
                ('periodo_prodes', models.CharField(null=True, blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TaxaNuvens',
            fields=[
                ('objectid', models.AutoField(serialize=False, primary_key=True)),
                ('mes', models.CharField(null=True, blank=True, max_length=10)),
                ('ano', models.SmallIntegerField(null=True, blank=True)),
                ('uf', models.CharField(null=True, blank=True, max_length=2)),
                ('area_km2', models.DecimalField(decimal_places=2, null=True, blank=True, max_digits=10)),
                ('porc_area_km2', models.DecimalField(decimal_places=0, null=True, blank=True, max_digits=2)),
                ('dat_cadastro', models.DateTimeField(null=True, blank=True)),
            ],
        ),
    ]
